### ISSUE TITLE
Crashing Problem, Need Help

### ISSUE THREAD

**Issue by DiabloDrake** [MoriyaShiine/extra-origins#129]
![Screenshot_61](https://user-images.githubusercontent.com/90275995/132596990-ede9bf0b-f1bb-4f7f-ab46-2ead2c03c233.png)

I keep on getting this error and the Origins mod creator has yet to respond so I hope you can help? Also here's the mod list.

![Screenshot_52](https://user-images.githubusercontent.com/90275995/132597062-b17aaeb6-6ebc-4951-b0d1-c47240d07bfc.png)

**Comment by MoriyaShiine** [comment]
I can't help without a crash report (exit codes are not a crash reports, you find those in the crash-reports folder), and you're also using an old version. The issue will be closed due to not using the latest version (1.17-6 as of now), but if you send the crash report (preferably via pastebin) then I can tell you the cause.

**Comment by DiabloDrake** [comment]
(The crash report as requested) https://pastebin.com/CZmVxi3H

But also, what are you referring to when you mention "due to not using the latest version (1.17-6 as of now)".

**Comment by MoriyaShiine** [comment]
Sorry for the late response, I haven't had access to my computer or phone. Updating Java (to 16) should fix the issue.
